/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 8.0.0   2017-11-04

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include "stm32f10x.h"
#include "stm32f10x_rcc.h"

#include "util.h"
#include "modules/recv.h"
#include "modules/iwdg.h"

int main(void)
{
	// Enable all GPIO ports so the other functions don't need to
	RCC->APB2ENR = RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN |
				   RCC_APB2ENR_AFIOEN;
	RCC->APB1ENR = RCC_APB1ENR_TIM3EN;

	// Initialize all primary modules
	recv_init();
	//mvmt_init();
	//wpn_init();

	// Initialize the independent watchdog
	iwdg_init();

	// Enable reception of signal data
	recv_enable();

	// Quick debugging feature
	RCC->APB1ENR |= RCC_APB1ENR_USART3EN;
	CONFIGURE_GPIO(GPIOB, 10, CFG_OUTPUT_ALTERNATE_PUSH_PULL_10MHZ);

	// Configure USART for 57600 baud rate
	USART3->BRR = 625;
	USART3->CR1 = USART_CR1_UE | USART_CR1_TE;

	int fr = 0;
	while (1)
	{
		recv_update();

		__WFI();
	}
}

// USART printf
int _write(int fd, char *str, int len)
{
	for (int i = 0; i < len; i++)
	{
		while (!(USART3->SR & USART_SR_TXE));
		USART3->DR = str[i];
	}

	return len;
}

void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
